project:
  type: website
  render:
    - "*.qmd"
    - "!posts"
  preview:
    port: 4200
    browser: true

website:
  title: "Hapax Analytics"
  image: images/_site/logo-hapax-v3.png
  favicon: images/_site/logo-hapax-v3.png
  site-url: https://hapax-la.netlify.app/
  search:
    algolia:
      index-name: prod_HAPAX
      application-id: VST6K5ZVS2
      search-only-api-key: b3ee25c09137dfab42531877f950403b
      analytics-events: true
      show-logo: true
  open-graph:
    locale: nl_NL
    site-name: Hapax Analytics
  cookie-consent: false
#    type: express
#    style: headline
#    palette: light
  navbar:
    title: Hapax Learning Analytics
    subtitle: Analytics in het hoger onderwijs
    logo: images/_site/logo-hapax-v3.png
    logo-alt: Hapax Analytics
    left:
      - text: Home
        href: index.qmd
      # - href: posts.qmd
      #  text: Blog
      - href: onderzoek.qmd
        text: Onderzoek
      - href: projecten.qmd
        text: Projecten
      - href: logboek.qmd
        text: Logboek
      - href: over.qmd
        text: Over
    right:
      - text: "{{< fa brands linkedin >}}"
        href: https://linkedin.com/in/theobakker
        aria-label: Linkedin
      - text: "{{< fa brands twitter >}}"
        href: https://twitter.com/tcbakker
        aria-label: Twitter
      - text: "{{< fa brands mastodon >}}"
        href: https://fosstodon.org/@tcbakker
        aria-label: Mastodon
      - text: "{{< fa brands github >}}"
        href: https://github.com/tcbakker
        aria-label: Github
      - text: "{{< fa regular envelope >}}"
        href: mailto:t.c.bakker@hhs.nl
        aria-label: Mail Theo Bakker via De HHs
      - text: "{{< fa solid square-rss >}}"
        href: index_posts.xml
        aria-label: RSS Feed
    pinned: true
  page-footer:
    border: true
    background: light
    left: "Gepubliceerd. met [Quarto](https://quarto.org/) <?quarto.version?> | &copy; 2023 [Hapax Analytics](/), [Theo Bakker](/over.html) | [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

filters:
  - lua/quarto-version.lua

execute:
  freeze: auto
