project:
  type: website
  render:
    - "*.qmd"
    - "!posts"
  preview:
    port: 4200
    browser: true

website:
  title: "Hapax Analytics"
  image: images/_site/logo-hapax-v3.png
  favicon: images/_site/logo-hapax-v3.png
  open-graph:
    locale: nl_NL
    site-name: Hapax Analytics
  site-url: https://hapax-analytics.nl/
  page-navigation: true
  search:
    algolia:
      index-name: "prod_HAPAX"
      application-id: EIZMHIKZAP
      search-only-api-key: bf138bbf5ec11025f0114f0358fa5822
      analytics-events: true
      show-logo: true
  page-footer:
    border: true
    background: light
    left: "Gepubliceerd. met [Quarto](https://quarto.org/) <?quarto.version?> | &copy; 2023 [Hapax Analytics](/), [Theo Bakker](/over.html) | [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"
  cookie-consent: false
#    type: express
#    style: headline
#    palette: light
  navbar:
    title: Hapax Analytics
    subtitle: Analytics in het hoger onderwijs
    logo: images/_site/logo-hapax-v3.png
    logo-alt: Hapax Analytics
    collapse-below: lg
    left:
      - text: Home
        href: index.qmd
      # - href: posts.qmd
      #  text: Blog
      - href: docs/onderzoek/onderzoek.qmd
        text: Onderzoek
      - href: docs/projecten/projecten.qmd
        text: Projecten
      - href: docs/logboek/logboek.qmd
        text: Logboek
      - href: docs/over/over.qmd
        text: Over
    right:
      - text: "{{< fa brands linkedin >}}"
        href: https://linkedin.com/in/theobakker
        aria-label: Linkedin
      - text: "{{< fa brands twitter >}}"
        href: https://twitter.com/tcbakker
        aria-label: Twitter
      - text: "{{< fa brands mastodon >}}"
        href: https://fosstodon.org/@tcbakker
        aria-label: Mastodon
      - text: "{{< fa brands github >}}"
        href: https://github.com/tcbakker
        aria-label: Github
      - text: "{{< fa regular envelope >}}"
        href: mailto:t.c.bakker@hhs.nl
        aria-label: Mail Theo Bakker via De HHs
      - text: "{{< fa solid square-rss >}}"
        href: index_posts.xml
        aria-label: RSS Feed
    pinned: true
  # sidebar:
  # - id: projecten

bibliography: citations/references.bib

format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    css: css/styles.css
    toc: true
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

editor: visual

filters:
  - lua/quarto-version.lua

execute:
  freeze: auto
